Develop lp
ICB-DCM/MEMOIR pull request #4
Opened 2017-05-10 13:52 UTC by paulstapor

If you have the time at some point, here is a pull-request from what we (Leonard and I) have changed on Memoir in our version so far.

The main interest of this pull request is not necessarily to merge it now, rather it is to see what has changed so far... and what should still be changed. Feel free to reject it.

Most probably, the changes in MEMfn/ could be omitted. I kept them here for simplicity.

2017-05-10 15:19 UTC, FFroehlich requested changes

2017-05-10 15:19 UTC, FFroehlich commented on getSimulationPA.m
> -%     SP = testSigmaPointApp(@(phi) simulateForSP(Model.exp{s}.model,Data{s}.PA.time,phi,Data{s}.condition),xi,Model.exp{s},op_SP);
ugh, some things from develop branch are included here and some are not :/ not really ideal
please set scale to lin op_SP.approx is not 'sp'

2017-05-10 15:19 UTC, FFroehlich commented on objective_phi.m
> +ny = sum(ind_y)*size(Ym,2);
are the problem that occur here fixed in #2 ?

2017-06-19 15:39 UTC, FFroehlich commented
please use more descriptive commit messages "little changes" and "minor changes" are almost equivalent to no commit message at all.

2017-07-04 15:18 UTC, FFroehlich commented
this pull request is continually growing and conflicts are piling up. please get to a functional version and merge as soon as possible. smaller chunks are easier to review and less error-prone for merging.

Also please adress the comments i had on the code (or at least comment that this is done/why it is not necessary).

2019-01-18 14:57 UTC, FFroehlich approved these changes

2019-01-18 14:57 UTC, FFroehlich commented on complete_model.m
> +        case {'matrix-logarithm', 'cholesky-parametrization'}
no filename for cholesky?

2019-01-18 14:57 UTC, FFroehlich commented on complete_model.m
> +                % Model.exp{s}.sym.dsigma_noisedphi(j,k,:) = jacobian(Model.exp{s}.sym.sigma_noise(j,k),phi);
remove comment?

2019-01-18 14:57 UTC, FFroehlich commented on make_model.m
> +    case {'matrix-logarithm', 'givens-parametrization', 'Lie-generators'}
cholesky?

2019-01-18 20:25 UTC, paulstapor commented on make_model.m
> +    case {'matrix-logarithm', 'givens-parametrization', 'Lie-generators'}
Not yet implemented, but it's on the list for a little study on efficiency. However, first things first...

2019-01-21 09:37 UTC, DantongWang approved these changes

2019-01-21 15:45 UTC, merged